language: ruby

bundler_args: "--binstubs --standalone --without documentation --path ../bundle"
script: "bundle exec rake test"
rvm:
  - 2.6.6
  - truffleruby
  - truffleruby-head
notifications:
  email: false
